### ISSUE TITLE
Regarding Portfolio preview

### ISSUE THREAD

**Issue by aletisunil** [8bithemant/Responsive-Portfolio#1]
I think this link https://hemant.codes/ is dead

**Comment by 8bithemant** [comment]
Hii Atilsunil,


Really sorry for that issue occurred, this was unpredictable for me, and your issue got me updated with this and figured out the issue with DNS related updation.

Lately I have been playing out with my DNS Address which broke the website too..

Thank you, will short out the issue shortly, keep an eye, on future changes.

**Comment by aletisunil** [comment]
Yes, Sure
